# This workflow executes a Python script to check for new updates for the linux-hardened package within the Arch Linux repositories. If a new update has been found, then the script extractes the files, generates a git commit, and finally pushes the new changes to this repository.
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  #
  # Triggers the workflow on every 0th, 3rd, 6th, 9th, 12th, 15th, 18th, and 21st hour
  schedule:
    - cron: "0 0,3,6,9,12,15,18,21 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Update the .spec file to the latest linux-hardened kernel version
        env:
          CI_COMMIT_AUTHOR: noatsecure
          CI_COMMIT_AUTHOR_EMAIL: noatsecure@protonmail.com
        run: python3 ci-kernel-hardened.py kernel-hardened.spec

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script 
      #  run: |
      #    echo "Hello world!"
